kind: Service
apiVersion: v1
metadata:
  name: alpha-service
spec:
  selector:
    app: alpha-service
  ports:
  - protocol: TCP
    port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpha-deploy
spec:
  selector:
      matchLabels:
        app: alpha-deploy
  replicas: 2
  template:
    metadata:
      labels:
        app: alpha-deploy
    spec:
      containers:
        - name: alpha-container
          image: localhost:5000/alpha-service:latest
          ports:
          - containerPort: 8080